### PR TITLE
Correcting ASCII character description & number

### PR DESCRIPTION
**Pull request by rudilee**
I don't know the exact font that used in graphic description, so i use Roboto which is the closest look that i can find

### CODE REVIEW

**Comment by yasserf** [comment]
I'm somewhat confused myself now!

```javascript
exports.MESSAGE_SEPERATOR = String.fromCharCode( 30 ); // ASCII Record Seperator 1E
exports.MESSAGE_PART_SEPERATOR = String.fromCharCode( 31 ); // ASCII Unit Separator 1F
```

```
return sendData.join( SEP ) + C.MESSAGE_SEPERATOR;

return topic + SEP + 'E' + SEP + type + SEP + message + C.MESSAGE_SEPERATOR;
```

Makes it look correct, since the seperate (31) is inbetween characters and (30) divides actual messages.

I think I might be getting myself confused though, can you let me know how your reached the conclusion they were wrong? Thanks!

**Comment by rudilee** [comment]
Hmm.. i'm getting even confusing now :confused:, from the original docs it says:

> **|** and **+** are used in these examples as placeholders, messages are actually separated by invisible Ascii control characters (**"record separator" (30)** and **"group seperator" (31)**)

but in the image it says **Invisible Record Separator (ASCII 31)** and **Invisible Group Separator (ASCII 30)**, so in the sentence it's 30 for record separator but it's 31 in the image, and 31 for group separator but 30 in the image.

And then silly me to assume that Group(Unit) Separator to divide the message chunk, and Record Separator to divide the message field, because of the order of the explanation of the control characters(record then group) doesn't match the placeholder order(| then +) :stuck_out_tongue: 

I conclude that the definition in the image is actually swapped then? if so i'll work on correcting the image and the explanation order then

N/B: So the typo is deeper(like source code level deep) than it look then, it suppose to be "separator" right?  :smile:

**Comment by rudilee** [comment]
I revert the wrong image corrections and added 2 commit for swapped definition corrections and matching order correction

**Comment by yasserf** [comment]
Awesome! I'll look into this asap, currently not near a pc

**Comment by yasserf** [comment]
Looks great, sorry for the late merge!

**Pull request merged**
