### PR TITLE
Elastic search

### PR DESCRIPTION
**Pull request by timaschew**

### CODE REVIEW

**Comment by yasserf** [comment]
We may want to use html instead.. currently partials do not work in the bulk file

**Comment by yasserf** [comment]
shouldn't refresh page on select
refreshes page to undefined

**Comment by timaschew** [comment]
> shouldn't refresh page on select
> refreshes page to undefined

done

**Comment by timaschew** [comment]
@WolframHempel looks very nice! 👍 
Just the font-weight for the search input looks blurry, maybe use a normal font-weight?

**Comment by WolframHempel** [comment]
Good point, will do

**Comment by timaschew** [comment]
Seems that the specs links are broken, e.g. I got redirected to http://localhost:3000/info/protocol/all-messages/all-messages.md which doesn't exist

**Pull request merged**
