### PR TITLE
Minimized Images

### PR DESCRIPTION
**Pull request by igeligel**
Since some images where really big and page load time was affected by big images i decided to minimize all images with the tools:

- [TinyPNG](https://tinypng.com/)
- [svgo](https://github.com/svg/svgo)

### CODE REVIEW

**Comment by yasserf** [comment]
This is awesome!

@julietmatsai how comfortable are you with doing a sanity check for this before we merge?

**Comment by julietmatsai** [comment]
@yasserf sure, will do it today

**Comment by julietmatsai** [comment]
@yasserf checked everything, looks fine to me, except:  

-[ ] the icon with Daniel looks a bit distorted here: /blog/deployment-using-terraform/

screen shot 2017-04-20 at 15 59 51

**Comment by yasserf** [comment]
@igeligel @julietmatsai apologies for the delay on this. We can live with the blog image distortion, if your happy with this we can merge it in!

**Pull request closed without merging**
