### PR TITLE
Fixed error in JS code example to emit an event

### PR DESCRIPTION
**Pull request by eduarddedu**
Emitting an event in the JS layer with just an name string - i.e. without passing some data object along - causes a MESSAGE_PARSE_ERROR: UNKNOWN_TYPE (U) to be thrown by a subscribed Java client. 

This is strange because the documentation for the JS client.event.emit(event, data) function
lists the data parameter as optional: [https://deepstream.io/docs/client-js/pubsub-client-event/](url)

Two possibilities: 

If the documentation is correct, then the tutorial is also fine, and it's actually the source code that needs to be amended. 

If the documentation has a bug, it should be corrected along with the tutorial.

### CODE REVIEW

**Comment by yasserf** [comment]
Actually this is a Java bug! Java doesn't have undefined as a concept, only null, so because of that it doesn't transform the type. The best solution would probably be to treat undefined as null.

**Comment by eduarddedu** [comment]
Yes, this is correct, Java doesn't have "undefined". Instance and class  variables are automatically initialised to null - if unassigned - and local variables need to be explicitly initialised or the compiler throws an error. 

So then the  java-client API would have to be changed to "treat undefined as null". Is this correct?  

I assume the behaviour can be implemented in the MessageParser.convertTyped() method: [https://github.com/deepstreamIO/deepstream.io-client-java/blob/master/src/main/java/io/deepstream/MessageParser.java](url)

static Object convertTyped( String value, DeepstreamClientAbstract client ) {

        char ch = value.charAt(0);
        Types type = Types.getType( ch );
        switch( type ) {
             case STRING :  
                      return value.substring( 1 );
             case NULL: 
             case UNDEFINED:
                       return null;
             case FLOAT : 
                      return Float.parseFloat( value.substring( 1 ) );
             ...etc
        }

(Note how switching on the enumerated type would improve readability). 

Should these changes be implemented in the java-client API? 

Thanks.

**Comment by yasserf** [comment]
This should now be fixed, haven't yet published the java client yet as we are going to do a couple days of testing first.

Btw, in the PR you used '{}' as a java object.. thats javascript syntax right? In java it would need to be new JsonObject() or something

**Comment by eduarddedu** [comment]
I used '{}' as JavaScript object notation, because I assumed that the event travels from JavaScript to Java. But the tutorial actually refers to a Java-publisher-to-Java-receiver scenario. Thanks for pointing this out and sorry about the mistake :)

To restate, the MESSAGE_PARSE_ERROR: UNKNOWN_TYPE (U) only occurs if 
- a JS publisher emits an event with client.event.emit('app');
- a subscribed Java client gets this empty event. 

The fix is to use client.event.emit('app', {});

**Pull request closed without merging**
