### PR TITLE
Sidebar fix/tweak

### PR DESCRIPTION
**Pull request by stevexm**
Change Sidebar layout and css so that it and the documentation article line up properly without overlap. Currently sidebar "hangs over" the article on smaller screens.
1) set .sidebar to fixed width of 250px
2) change sidebar layout removing div.hack wrapper, not needed if using fixed width
3) personal styling changes for sidebar; no background, border and padding: 50px 20px
4) set .article width to calc(100% - 250px) so that the documentation article and sidebar line up without overlapping
5) personal styling changes; add .article padding all round and a border on the right side that runs the height of the documentation article
6) set .wrapper max-width: 1440px and .article max-width: 1200px

Thanks for making DeepStream available, a great resource. Hope this helps and contributes to continued community support!

### CODE REVIEW

**Comment by yasserf** [comment]
Thank you for raising! It seems the files however are all based in the root directory, which means they won't actually apply to the build or website. Could you please put them in the correct place?

Many thanks!

**Comment by stevexm** [comment]
Hello Yasser, good morning from Australia. Happy to relocate the files to the source directory, apologies for that. I will try and get to it later today, which is going to be a busy one.

 
Warm regards, Steve

 
Steve Melnikoff
Chief Scientist
ADD | Melbourne, Australia
CN | +61+417347189

E-mail | steve.melnikoff@penta.global

Web  | https://www.penta.global/

 PENTA

The Universal Blockchain Connector

-----Original message-----

**Review by stevexm — COMMENTED** [review]
Apologies again for uploading to root; fixed
(1) Relocated uploads to proper src/components/Markdown/  MarkdownContent/ and SideBar/
(2) Added @media print css so sidebar not shown as well as footer navigation

**Comment by yasserf** [comment]
Incredible thank you!

**Pull request merged**
